/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeLinux */

#ifndef _Included_NativeLinux
#define _Included_NativeLinux
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeLinux
 * Method:    mygetpid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_NativeLinux_mygetpid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
